# https://docs.github.com/en/actions/guides
# CI name , it will display on github's action page menu
name: SpringBootDemo
# trigger on which this CI should be run
on: # push operation is operate
  push:
    # here since my repository branch is named `main` , you should follow your own repository like `master`
    branches: [main]
# CI enviroment settings
env:
  STATE_RELEASE_VERSION: "1.0" # version
  TAG_NAME: "springcloud_multi_module" #tag 只能小写开头
  java-version: "11"
jobs:
  build:
    name: 构建并生成producer docker image
    runs-on: ubuntu-latest # use latest ubuntu to run the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java-version }}
      - name: Build with Maven
        run:
          mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: show files
        run: ls -a
      - name: show one_module files
        run: cd one_module && ls -a
      - name: show one_module/target files
        run: cd one_module && cd target && ls -a
      - name: Output Docker info
        run: docker info
      - name: Sets build date
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #版本号第一位不允许空格
      - name: Push Producer Image to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: one_module/Dockerfile
          tags: "includeno/${{ env.TAG_NAME }}producer:latest,includeno/${{ env.TAG_NAME }}producer:${{ env.STATE_RELEASE_VERSION }}"
          push: true
      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "success"
  build2:
    name: 构建并生成comsumer docker image
    runs-on: ubuntu-latest # use latest ubuntu to run the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java-version }}
      - name: Build with Maven
        run:
          mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: show files
        run: ls -a
      - name: show two_module files
        run: cd two_module && ls -a
      - name: show two_module/target files
        run: cd two_module && cd target && ls -a
      - name: Output Docker info
        run: docker info
      - name: Sets build date
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #版本号第一位不允许空格
      - name: Push Spider Image to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: two_module/Dockerfile
          tags: "includeno/${{ env.TAG_NAME }}comsumer:latest,includeno/${{ env.TAG_NAME }}comsumer:${{ env.STATE_RELEASE_VERSION }}"
          push: true
      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "success"